baseurl = "/"
title = "Guohao's Blog"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
# disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "UA-156444600-1" # Enable Google Analytics by entering your tracking id

[Params]
  subtitle = "Another me in a foreign land" # Subtitle of your site. Used in site header
  description = "Guohao Zhang's Personal blog about everything" # Site description. Used in meta description
  copyright = "Guohao Zhang" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["java", "leetcode", "distributed-system", "algorithm", "career"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
#   customCSS = ["css/custom.css"] # Include custom CSS files
#   customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
#   facebook = "username"
#   twitter = "username"
#   instagram = "username"
#   linkedin = "username"
#   telegram = "username"
  github = "gwokhou"
#   gitlab = "username"
#   bitbucket = "username"
  email = "akidezhang@outlook.com"
